---
- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: Create real server for test preparation
      fadcos_real_server:
       action: add
       name: test_rs
       ip: 6.6.6.6
       status: enable
       vdom: root
    - name: Create real server pool for test preparation
      fadcos_real_server_pool:
        action: add
        name: test_rs_pool
        iptype: ipv4
        vdom: root
        healthcheck: enable
        health_check_list:
           - LB_HLTHCK_ICMP
           - LC_HLTHCK_HTTPS
        rs_profile: test_server_ssl_profile 
    - name: delete a member to prepare for a test
      fadcos_real_server_pool_member:
        action: delete
        pool_name: test_rs_pool
        member_id: 1
    - name: Create real server pool member
      fadcos_real_server_pool_member:
        action: add
        pool_name: test_rs_pool
        member_id: 1
        rs: test_rs
    - name: Create a duplicated real server pool member
      fadcos_real_server_pool_member:
        action: add
        pool_name: test_rs_pool
        member_id: 1
        rs: test_rs
    - name: check the server pool member
      fadcos_real_server_pool_member:
        action: get 
        pool_name: test_rs_pool
        member_id: 1
    - name: edit the real server pool member
      fadcos_real_server_pool_member:
        action: edit
        pool_name: test_rs_pool
        member_id: 1
        health_check: enable
    - name: check the server pool member after edit
      fadcos_real_server_pool_member:
        action: get 
        pool_name: test_rs_pool
        member_id: 1
    - name: delete a member to finish the test
      fadcos_real_server_pool_member:
        action: delete
        pool_name: test_rs_pool
        member_id: 1
    - name: delete a member twice to test idempotency 
      fadcos_real_server_pool_member:
        action: delete
        pool_name: test_rs_pool
        member_id: 1
    - name: check the server pool member after delete
      fadcos_real_server_pool_member:
        action: get 
        pool_name: test_rs_pool
        member_id: 1