---
- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: remove to prepare the test and check whether removing non-existent stuff causes error
      fadcos_system_snmp_community:
       action: remove
       id_list:
            - '1'
            - '2'
            - '3'
            - '4'

    - name: add
      fadcos_system_snmp_community:
       action: add
       name: test
       query_v1_port: '101'
       query_v1_status: enable
       query_v2c_port: '101'
       query_v2c_status: enable

    - name: duplicated add to test idempotency
      fadcos_system_snmp_community:
       action: add
       name: test1
       query_v1_port: '102'
       query_v1_status: disable
       query_v2c_port: '102'
       query_v2c_status: enable
       id: 1

    - name: add another test subject
      fadcos_system_snmp_community:
       action: add
       name: test3
       query_v1_port: '111'
       query_v1_status: enable
       query_v2c_port: '111'
       query_v2c_status: enable

    - name: check the result of add
      fadcos_system_snmp_community:
       action: get

    - name: edit
      fadcos_system_snmp_community:
       action: edit
       id: '1'
       query_v1_port: '162'
       query_v1_status: disable
       query_v2c_port: '162'
       query_v2c_status: disable

    - name: edit a non-existent entry
      fadcos_system_snmp_community:
       action: edit
       id: '99'
       query_v1_port: '162'
       query_v1_status: disable
       query_v2c_port: '162'
       query_v2c_status: disable

    - name: get
      fadcos_system_snmp_community:
       action: get

    - name: remove to finish the test
      fadcos_system_snmp_community:
       action: remove
       id_list:
            - '1'
            - '2'
            - '3'
            - '4'

    - name: check whether removing is clear
      fadcos_system_snmp_community:
       action: get