---
- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: Add the real server pool for test
      fadcos_real_server_pool:
        action: edit
        name: rs_pool_tst
        iptype: ipv4
        vdom: root
        healthcheck: enable
        health_check_list:
                - LB_HLTHCK_HTTPS
                - LB_HLTHCK_ICMP  
    - name: Create basic virtual server
      fadcos_virtual_server_basic:
       name: test
       application: http
       address: 7.7.7.7
       interface: port3
       pool: rs_pool_tst
       port: 80
    - name: Create basic virtual server again
      fadcos_virtual_server_basic:
       name: test
       application: http
       address: 7.7.7.7
       interface: port3
       pool: rs_pool_tst
       port: 80