---
- name:
  hosts: all
  connection: httpapi
  gather_facts: false
  tasks:
    - name: Add Local Certificate Group Test1
      fadcos_local_cert_group:
        action: add_group
        name: ansible_test_G1
    - name: Add Local Certificate Group Test2
      fadcos_local_cert_group:
        action: add_group
        name: ansible_test_G2
    - name: Add duplicated Local Certificate Group
      fadcos_local_cert_group:
        action: add_group
        name: ansible_test_G2
    - name: Delete Local Certificate Group
      fadcos_local_cert_group:
        action: delete_group
        name: ansible_test_G1
    - name: Get the deleted Local Certificate Group ansible_test_G1
      fadcos_local_cert_group:
        action: get_group
        name: ansible_test_G1
    - name: Get Local Certificate Group
      fadcos_local_cert_group:
        action: get_group
        name: ansible_test_G2
    - name: Add Local Certificate Group Members test
      fadcos_local_cert_group:
        action: add_member
        name: ansible_test_G2
    - name: Add duplicated Local Certificate Group Members test
      fadcos_local_cert_group:
        action: add_member
        name: ansible_test_G2
    - name: Get Local Certificate Group Members after repeating member addition
      fadcos_local_cert_group:
        action: get_member
        name: ansible_test_G2
    - name: Delete Local Certificate Group Members test
      fadcos_local_cert_group:
        action: delete_member
        name: ansible_test_G2
        member_id: 1
    - name: Repeat deleting Local Certificate Group Members test 
      fadcos_local_cert_group:
        action: delete_member
        name: ansible_test_G2
        member_id: 1
    - name: Get Local Certificate Group Members
      fadcos_local_cert_group:
        action: get_member
        name: ansible_test_G2
