---
- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:  
    - name: add object cert
      fadcos_cert_verify:
       action: add_object
       name: ca1
    - name: add an duplicated object cert
      fadcos_cert_verify:
       action: add_object
       name: ca1
    - name: get object cert
      fadcos_cert_verify:
       action: get_object
       name: ca1
    - name: delete_object cert
      fadcos_cert_verify:
       action: delete_object
       name: ca1
    - name: delete_object cert again to test idempotency
      fadcos_cert_verify:
       action: delete_object
       name: ca1
    - name: check the result of delete action
      fadcos_cert_verify:
       action: get_object
       name: ca1
    - name: add object cert for member test
      fadcos_cert_verify:
       action: add_object
       name: test_object
    - name: Add Certificate Verification Object Member
      fadcos_cert_verify:
        action: add_member
        name: test_object
        ca: Fortinet_CA
        member_id: 42
    - name: Test added Certificate Verification Object Member
      fadcos_cert_verify:
        action: get_member
        name: test_object
        ca: Fortinet_CA
        member_id: 42
    - name: Get a non-existent cert object
      fadcos_cert_verify:
        action: get_member
        name: test_object
        ca: Fortinet_CA
        member_id: 462
    - name: Add Duplicated Certificate Verification Object Member
      fadcos_cert_verify:
        action: add_member
        name: test_object
        ca: Fortinet_CA
        member_id: 42
    - name: Test duplicately added Certificate Verification Object Member
      fadcos_cert_verify:
        action: get_member
        name: test_object
        ca: Fortinet_CA
        member_id: 42
    - name: Delete Certificate Verification Object Member
      fadcos_cert_verify:
        action: delete_member
        name: test_object
        ca: Fortinet_CA
        member_id: 42
    - name: Delete again Certificate Verification Object Member to test idempotency
      fadcos_cert_verify:
        action: delete_member
        name: test_object
        ca: Fortinet_CA
        member_id: 42
    - name: Test duplicately Deleted Certificate Verification Object Member
      fadcos_cert_verify:
        action: get_member
        name: test_object
        ca: Fortinet_CA
        member_id: 42


# EXAMPLES = """
# - name:
#   hosts: all
#   connection: httpapi
#   gather_facts: false
#   tasks:
#     - name: Manage Certificate Verification Object
#       fadcos_cert_verify:
#         action: add_object
#         name: test_object
#     - name: Manage Certificate Verification Object Member
#       fadcos_cert_verify:
#         action: add_member
#         name: test_object
#         ca: Fortinet_CA
# """