---
- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: Create nat pool
      fadcos_nat_pool:
        action: add
        name: natpool
        interface: port1
        iptype: ipv4
        ipstart: 192.168.2.100
        ipend: 192.168.2.200
    - name: Create nat poot test1
      fadcos_nat_pool_member:
        action: add
        natpool_name: natpool
        name: test1
        interface: port1
        pooltype: ipv4
        ipmin: 192.168.2.102
        ipmax: 192.168.2.110
    - name: Create duplicated nat poot test1
      fadcos_nat_pool_member:
        action: add
        natpool_name: natpool
        name: test1
        interface: port1
        pooltype: ipv4
        ipmin: 192.168.2.112
        ipmax: 192.168.2.120
    - name: Check nat poot
      fadcos_nat_pool_member:
        action: get
        natpool_name: natpool
        name: test1
    - name: Edit nat poot test1
      fadcos_nat_pool_member:
        action: edit
        natpool_name: natpool
        name: test1
        interface: port1
        pooltype: ipv4
        ipmin: 192.168.2.150
        ipmax: 192.168.2.160
    - name: Edit nat poot non-existent
      fadcos_nat_pool_member:
        action: edit
        natpool_name: natpool
        name: test1123
        interface: port1
        pooltype: ipv4
        ipmin: 192.168.2.180
        ipmax: 192.168.2.188
    - name: Check nat poot after edit
      fadcos_nat_pool_member:
        action: get
        natpool_name: natpool
        name: test1
    - name: Delete nat poot test1
      fadcos_nat_pool_member:
        action: delete
        natpool_name: natpool
        name: test1
    - name: Delete nat poot test2 again to ensure deletetion of non-existent entry does not cause error.
      fadcos_nat_pool_member:
        action: delete
        natpool_name: natpool
        name: test1
    - name: Check nat poot after delete action
      fadcos_nat_pool_member:
        action: get
        natpool_name: natpool
        name: test1

