---
- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: delete virtual server to prepare a new test
      fadcos_virtual_server:
       action: delete
       name: test_vs
    - name: check virtual server to ensure it is deleted
      fadcos_virtual_server:
       action: get
       name: test_vs
    - name: delete virtual server again to test whether there is error
      fadcos_virtual_server:
       action: delete
       name: test_vs
    - name: Add the real server pool for test
      fadcos_real_server_pool:
        action: edit
        name: rs_pool_tst
        iptype: ipv4
        vdom: root
        healthcheck: enable
        health_check_list:
                - LB_HLTHCK_HTTPS
                - LB_HLTHCK_ICMP  
    - name: Add virtual server
      fadcos_virtual_server:
       action: add
       name: test_vs
       status: enable
       iptype: ipv4
       ip: 7.7.7.1
       interface: port3
       pool: rs_pool_tst
       port: 80
       profile: LB_PROF_TCP
       vstype: l4-load-balance
    - name: check virtual server to ensure it is added
      fadcos_virtual_server:
       action: get
       name: test_vs
    - name: Add the duplicated virtual server
      fadcos_virtual_server:
       action: add
       name: test_vs
       status: enable
       iptype: ipv4
       ip: 8.8.8.8
       interface: port2
       pool: rs_pool_tst
       port: 8080
       profile: LB_PROF_TCP
       vstype: l4-load-balance
    - name: check the result of duplication add of virtual server
      fadcos_virtual_server:
       action: get
       name: test_vs
    - name: Edit virtual server
      fadcos_virtual_server:
       action: edit
       name: test_vs
       status: enable
       iptype: ipv4
       ip: 6.6.6.1
       interface: port2
       pool: rs_pool_tst
       port: 80
       profile: LB_PROF_TCP
       vstype: l4-load-balance
    - name: check virtual server to ensure it is edited
      fadcos_virtual_server:
       action: get
       name: test_vs
    - name: delete virtual server
      fadcos_virtual_server:
       action: delete
       name: test_vs
    - name: check virtual server to ensure it is deleted
      fadcos_virtual_server:
       action: get
       name: test_vs