---
- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: delete real server to prepare test
      fadcos_real_server:
       action: delete
       name: rs
    - name: see whether it is deleted
      fadcos_real_server:
       action: get
       name: rs
    - name: delete non-existent real server to see whether there is error
      fadcos_real_server:
       action: delete
       name: rs
    - name: Add real server test subject 
      fadcos_real_server:
       action: add
       name: rs
       ip: 6.6.6.5
       status: enable
       vdom: root
    - name: see whether the add action is success
      fadcos_real_server:
       action: get
       name: rs
    - name: Add duplcated real server 
      fadcos_real_server:
       action: add
       name: rs
       ip: 3.3.3.3
       status: enable
       vdom: root
    - name: see whether the duplicated add action is success
      fadcos_real_server:
       action: get
       name: rs
    - name: edit real server 
      fadcos_real_server:
       action: edit
       name: rs
       ip: 3.3.3.4
       status: disable
       vdom: root
    - name: see whether the edit action is success
      fadcos_real_server:
       action: get
       name: rs
    - name: delete real server to prepare test
      fadcos_real_server:
       action: delete
       name: rs
    - name: see whether it is deleted
      fadcos_real_server:
       action: get
       name: rs