---
- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: Delete route static for new test
      fadcos_route_static:
        action: delete
        route_id: 123
    - name: Check route static still exists
      fadcos_route_static:
        action: get 
        route_id: 123
    - name: Delete route static again to see whether delete non-existent entry causes error
      fadcos_route_static:
        action: delete
        route_id: 123
    - name: Add route satatic
      fadcos_route_static:
       action: add
       route_id: 123
       desination: 66.1.1.0/24
       gateway: 66.1.1.254
       distance: 10
       vdom: root
    - name: Check newly added route static
      fadcos_route_static:
        action: get 
        route_id: 123
    - name: Add duplicated route satatic
      fadcos_route_static:
       action: add
       route_id: 123
       desination: 77.2.2.0/24
       gateway: 77.2.2.254
       distance: 10
       vdom: root
    - name: Check newly added duplicated route static
      fadcos_route_static:
        action: get 
        route_id: 123
    - name: Edit route satatic
      fadcos_route_static:
       action: edit
       route_id: 123
       desination: 88.3.3.0/24
       gateway: 88.3.3.254
       distance: 10
       vdom: root
    - name: Check newly edited route static
      fadcos_route_static:
        action: get 
        route_id: 123
    - name: Delete route static to finish test
      fadcos_route_static:
        action: delete
        route_id: 123
    - name: Check route static still exists
      fadcos_route_static:
        action: get 
        route_id: 123
