---
- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: add a test subject
      fadcos_error_page:
       action: add
       name: test2
       vpath: /fortiadc_error_page/
       srcfile: errpage.tar

    - name: add a duplicated test subject to test idempotency
      fadcos_error_page:
       action: add
       name: test2
       vpath: /fortiadc_error_page_1/
       srcfile: errpage.tar

    - name: check the test subject
      fadcos_error_page:
       action: get

    - name: edit a existed page
      fadcos_error_page:
       action: edit
       name: test2
       vpath: /fortiadc_error_page_changed/
       srcfile: errpage.tar

    - name: edit a non-exist subject
      fadcos_error_page:
       action: edit
       name: test12313322
       vpath: /fortiadc_error_pages_changed/

    - name: check the test subject after edit
      fadcos_error_page:
       action: get

    - name: remove test 
      fadcos_error_page:
       action: remove
       names:
           - test2

    - name: get
      fadcos_error_page:
       action: get

    - name: remove a non-exist entry 
      fadcos_error_page:
       action: remove
       names:
           - test2