---
- name:
  hosts: all
  connection: httpapi
  gather_facts: false
  tasks:
    - name: Add interface
      fadcos_interface:
       action: edit
       name: testport
       mode: static
       intf_type: vlan
       interface: port1
       vlanid: 100
       IPandMask: 22.33.192.241/24
       allowaccess:
               - snmp
               - http
       #vdom: root
    - name: get interface
      fadcos_interface:
       action: get
    - name: Add interface again to test idempotency
      fadcos_interface:
       action: add
       name: testport
       mode: static
       intf_type: vlan
       interface: port4
       vlanid: 100
       IPandMask: 17.16.192.241/24
       allowaccess:
               - snmp
               - http
    - name: get interface
      fadcos_interface:
       action: get
    - name: Edit interface
      fadcos_interface:
       action: edit
       name: testport
       mode: static
       intf_type: vlan
       interface: port2
       vlanid: 99
       IPandMask: 22.33.192.241/24
       allowaccess:
               - snmp
               - http
    - name: Edit a non-exist interface
      fadcos_interface:
       action: edit
       name: testport
       mode: static
       intf_type: vlan
       interface: port2
       vlanid: 123
       IPandMask: 22.33.44.55/24
       allowaccess:
               - snmp
               - http
    - name: get interface
      fadcos_interface:
       action: get
    - name: delete interface
      fadcos_interface:
       action: delete
       name: testport
    - name: check whether the interface is deleted
      fadcos_interface:
       action: get
    - name: delete a non-existent interface
      fadcos_interface:
       action: delete
       name: testport


