---
- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: create
      fadcos_load_balance_persistence:
       action: add
       name: test12
       type: radius-attribute
       timeout: 400
       match_across_servers: enable
       override_connection_limit: enable
       radius_attribute_relation: OR

    - name: add test
      fadcos_load_balance_persistence_child_radius_attribute:
       action: add
       name: test12
       type: 1-user-name
       id: '1'

    - name: add duplicated item test
      fadcos_load_balance_persistence_child_radius_attribute:
       action: add
       name: test12
       type: 43-acct-output-octets
       id: '1'

    - name: add test 2
      fadcos_load_balance_persistence_child_radius_attribute:
       action: add
       name: test12
       type: 63-login-lat-port
       id: '2'


    - name: edit
      fadcos_load_balance_persistence_child_radius_attribute:
       action: edit
       name: test12
       type: 1-user-name
       id: '1'

    - name: edit non-exist test
      fadcos_load_balance_persistence_child_radius_attribute:
       action: edit
       name: test12
       type: 40-serv-restrict-code
       id: '9999'

    - name: get
      fadcos_load_balance_persistence_child_radius_attribute:
       action: get
       name: test12

    - name: remove
      fadcos_load_balance_persistence_child_radius_attribute:
       action: remove
       name: test12
       id_list:
            - '1'
            - '2'
            - '3'
            - '4'

    - name: get
      fadcos_load_balance_persistence_child_radius_attribute:
       action: get
       name: test12
      

