---
- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: add vdom
      fadcos_vdom:
       action: add
       name: ansible_vdom
    - name: add vdom again to test idempotency
      fadcos_vdom:
       action: add
       name: ansible_vdom
    - name: get vdom to prepare for test
      fadcos_vdom:
       action: get
       name: ansible_vdom
    - name: delete vdom to finish test
      fadcos_vdom:
       action: delete
       name: ansible_vdom
    - name: delete vdom again to test idempotency
      fadcos_vdom:
       action: delete
       name: ansible_vdom
    - name: get vdom to check whether delete is successful
      fadcos_vdom:
       action: get
       name: ansible_vdom