---
- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: Add Health Checks
      fadcos_health_check:
        action: add
        name: test_hc2
        dest_addr_type: ipv4
        dest_addr: 7.7.7.7
        up_retry: 3
        down_retry: 6
        interval: 5
        timeout: 3
        hc_type: icmp
    - name: Add a duplicated Health Checks
      fadcos_health_check:
        action: add
        name: test_hc2
        dest_addr_type: ipv4
        dest_addr: 5.5.5.5
        up_retry: 1
        down_retry: 3
        interval: 5
        timeout: 3
        hc_type: icmp
    - name: View Health Checks
      fadcos_health_check:
        action: get
        name: test_hc2
    - name: Edit Health Checks
      fadcos_health_check:
        action: edit
        name: test_hc2
        dest_addr_type: ipv4
        dest_addr: 6.7.8.9
        up_retry: 2
        down_retry: 6
        interval: 8
        timeout: 4
        hc_type: icmp
    - name: View Health Checks after edit
      fadcos_health_check:
        action: get
        name: test_hc2
    - name: Edit a non-existent Health Checks
      fadcos_health_check:
        action: edit
        name: test_hc_nothere
        dest_addr_type: ipv4
        dest_addr: 7.7.7.7
        up_retry: 3
        down_retry: 6
        interval: 8
        timeout: 4
        hc_type: icmp
    - name: Delete Health Checks
      fadcos_health_check:
        action: delete
        name: test_hc2
    - name: Check whether Health Checks is deleted
      fadcos_health_check:
        action: get
        name: test_hc2
    - name: Delete non-existent entry
      fadcos_health_check:
        action: delete
        name: test_hc2
