---
- name:
  hosts: all
  vars:
  connection: httpapi
  gather_facts: false
  tasks:
    - name: Create a real server pool as the test subject
      fadcos_real_server_pool:
        action: add
        name: rs_pool
        iptype: ipv6
        vdom: root
        healthcheck: enable
        health_check_list:
                - LB_HLTHCK_HTTPS
    - name: create content routing
      fadcos_load_balance_content_routing:
       action: edit
       name: test1
       type: l7-content-routing
       ip: 172.23.133.178/24
       method_inherit: disable
       method: LB_METHOD_LEAST_CONNECTION
       persistence_inherit: enable
       persistence: LB_PERSIS_HASH_SRC_ADDR
       schedule_list: disable
       pool: rs_pool
       comments: nothings
    - name: create test without id 
      fadcos_load_balance_content_routing_child_match_condition:
       action: add
       name: test1
       type: string
       reverse: disable
       ignorecase: "enable"
       content: match
       object: http-host-header
    - name: create test with a exist entry to test idempotency
      fadcos_load_balance_content_routing_child_match_condition:
       action: add
       name: test1
       type: string
       reverse: disable
       ignorecase: "enable"
       content: match
       object: http-host-header
       id: 1
    - name: edit test
      fadcos_load_balance_content_routing_child_match_condition:
       action: edit
       name: test1
       content: match
       ignorecase: enable
       object: http-host-header
       reverse: disable
       type: string
       id: 1
    - name: check added and edited entries
      fadcos_load_balance_content_routing_child_match_condition:
       action: get
       name: test1
    - name: edit another entry
      fadcos_load_balance_content_routing_child_match_condition:
       action: edit
       name: test1
       type: string
       content: match
       ignorecase: disable
       reverse: disable
       object: sni
       id: 2
    - name: edit a non-existent entry
      fadcos_load_balance_content_routing_child_match_condition:
       action: edit
       name: test1
       type: string
       content: match
       ignorecase: disable
       reverse: disable
       object: sni
       id: 9999
    - name: get
      fadcos_load_balance_content_routing_child_match_condition:
       action: get
       name: test
    - name: delete
      fadcos_load_balance_content_routing_child_match_condition:
       action: remove
       name: test1
       id_list:
            - '1'
            - '2'
            - '3'
            - '4'
            - '5'
            - '6'
            - '99999'

